import { type NextPage } from "next";
import Head from "next/head";
import Feed from "../components/Feed";

const Home: NextPage = () => {
  return (
    <div className="scrollbar-hide col-span-7 min-h-screen overflow-scroll border-x lg:col-span-5">
      <Head>
        <title>T3 twitter clone app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Feed />
    </div>
  );
};

export default Home;
